WARNINGS := -Wall -Wextra -Wc++-compat
LOG := sh -c 'printf "\\t$$0\\t$$1\\n"'

HEADERS := \
		include/cc_alloc.h \
		include/cc_assert.h \
		include/cc_defs.h \
		include/cc_disp.h \
		include/cc_inttypes.h \
		include/cc_inttypes.user.h \
		include/cc_list.h \
		include/cc_panic.h \
		include/cc_string.h \
		include/cc_vec.h \
		out/test/cfg.h

SOURCES := \
		src/cc_alloc.c \
		src/cc_assert.c \
		src/cc_disp.c \
		src/cc_list.c \
		src/cc_panic.c \
		src/cc_string.c \
		src/cc_vec.c \
		src/cclib/cc_alloc.cclib.c \
		src/cclib/cc_string.cclib.c \
		src/std/cc_alloc.std.c \
		src/std/cc_string.std.c

.PHNOY: test_cc_vec vg_cc_vec
test_cc_vec: out/test/test_cc_vec
	@$(LOG) TEST out/test/test_cc_vec
	@./out/test/test_cc_vec

vg_cc_vec: out/test/test_cc_vec
	@$(LOG) VG out/test/test_cc_vec
	@valgrind --leak-check=full ./out/test/test_cc_list

out/test/test_cc_vec: out/test test/test_cc_vec.c $(SOURCES) $(HEADERS)
	@$(LOG) CC test/test_cc_vec.c
	@$(CC) $(CFLAGS) $(WARNINGS) -g \
		src/cc_vec.c \
		src/cc_assert.c \
		src/cc_disp.c \
		src/cc_panic.c \
		src/std/cc_alloc.std.c \
		src/std/cc_string.std.c \
		test/test_cc_vec.c \
		-I include/ -I out/test -I test/ \
		-o out/test/test_cc_list

.PHONY: test_cc_list vg_cc_list
test_cc_list: out/test/test_cc_list
	@$(LOG) TEST out/test/test_cc_list
	@./out/test/test_cc_list

vg_cc_list: out/test/test_cc_list
	@$(LOG) VG out/test/test_cc_list
	@valgrind --leak-check=full ./out/test/test_cc_list

out/test/test_cc_list: out/test test/test_cc_list.c $(SOURCES) $(HEADERS)
	@$(LOG) CC test/test_cc_list.c
	@$(CC) $(CFLAGS) $(WARNINGS) -g \
		src/cc_list.c \
		src/cc_assert.c \
		src/cc_disp.c \
		src/cc_panic.c \
		src/std/cc_alloc.std.c \
		src/std/cc_string.std.c \
		test/test_cc_list.c \
		-I include/ -I out/test/ -I test/ \
		-o out/test/test_cc_list

out/test/cfg.h: out/test cfg.temp.h
	@$(LOG) CP cfg.temp.h
	@cp cfg.temp.h out/test/cfg.h

out/test:
	@$(LOG) MKDIR out/test
	@mkdir -p out/test

